"""Init

Revision ID: 4a1479130e68
Revises: 7755264e664a
Create Date: 2025-07-20 00:23:10.060542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1479130e68'
down_revision: Union[str, Sequence[str], None] = '7755264e664a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'alembic_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('alembic_test', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
